### ISSUE TITLE
Provide example for Configuration and project-specific settings

### ISSUE THREAD

**Issue by raulpoppiel** [hooge104/geospatial_mapping_pipeline#1]
Dear author(s),

I have many doubts about what information should be filled in several lines in the "Configuration and project-specific settings" section of your code. Perhaps, you can provide an example with such information filled in to help users.

Specifically, I do not know what should be written in the following item (lines 53 and 54):
53 bashFunction_EarthEngine = ''
54 bashFunctionGSUtil = ''

Congrats for this very useful pipeline!
Thank you
Raul

**Comment by hooge104** [comment]
Thanks for the comment. Those lines should direct to the location on your local computer where you have installed 'earthengine-api' and 'gsutil'. I've updated the annotations in the script.
